//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transport_API
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Заказ
    {
        public int id_заказа { get; set; }
        public Nullable<decimal> Сумма_заказа { get; set; }
        public string Состояние_заказа { get; set; }
        public Nullable<int> id_клиента { get; set; }
        public Nullable<int> id_товара { get; set; }
        public Nullable<int> id_Транспорта { get; set; }
        [JsonIgnore]
        public virtual Клиент Клиент { get; set; }
        [JsonIgnore]
        public virtual Товары Товары { get; set; }
        [JsonIgnore]
        public virtual Транспорт Транспорт { get; set; }
    }
}
