//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace transport_API
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Скидки
    {
        public int id_скидки { get; set; }
        public Nullable<int> Процент_скидки { get; set; }
        public Nullable<System.DateTime> Длительность { get; set; }
        public Nullable<int> id_Товара { get; set; }
        [JsonIgnore]
        public virtual Товары Товары { get; set; }
    }
}
